@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
' uncomment the following line and comment the first to use locally
' !include C4_Container.puml

' LAYOUT_TOP_DOWN()
' LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()

title Диаграмма проекта "Система учета и списания подарочных сертификатов/бонусная система"

Person(клиент, клиент, "покупатель")

System_Boundary(c1, "Приложение фронт") {
    Container(ДокРеализация, "Документ 'Реализация товаров и услуг'", "", "Оформление документа продажи товаров и услуг.")
    ContainerDb(фронт_бд, "БД фронта", "", "Хранение данных фронт-офисного приложения")
}

System_Boundary(c2, "Приложение бэк") {
     Container(httpсервис, "http сервис по обслуживанию вирт. карт", "Получение баланса карты, списание с баланса во время продажи", "")   
     Container(ДанныеКарт, "РН 'Баланс Виртуальных карт'", "", "Хранение баланса по картам")
     Container(Карты, "Справочник 'Виртуальные карты'", "", "Хранение данных по вирт. картам")            
     ContainerDb(бэк_бд, "БД бэка", "", "Хранение данных бэк-офисного приложения")
     
}

System_Boundary(c3, "Брокер сообщений") {
     Container(Очередь, "Очередь обмена сообщениями", "exc_1c", "")    
     ContainerDb(БазаБрокера, "БД брокера сообщений", "", "Хранение данных бэк-офисного приложения")
}

Rel(клиент, ДокРеализация, "Оформление документа продажи", "запрос номера телефона для поиска карты")
Rel(ДокРеализация, фронт_бд, "", "TCP")
Rel(бэк_бд, клиент, "Оповещение клиента о состоянии баланса его бонусной карты", "email/SMS")

Rel(ДокРеализация, httpсервис, "Запрос данных вирт. карт", "http")
Rel(httpсервис, ДанныеКарт, "Сохранение баланса вирт. карт", "")
Rel(httpсервис, Карты, "Сохранение данных вирт. карт", "")
Rel(Карты, бэк_бд, "Сохранение баланса вирт. карт", "")
Rel(ДанныеКарт, бэк_бд, "Сохранение баланса вирт. карт", "")

Rel(Очередь, БазаБрокера, "Сохранение сообщений в базу брокера", "")
Rel(бэк_бд, Очередь, "Сохранение сообщений в базу брокера", "HTTPS/TCP")
Rel(фронт_бд, Очередь, "Обмен данными между системами черед брокер", "HTTPS/TCP")

@enduml